/*
================================================================================
QR STUDIO - VITE CONFIGURATION
================================================================================

File: vite.config.ts
Description: Vite build configuration for both web and Wails desktop builds.
             Supports dual-mode development: pure web SPA and Wails desktop app.

Build Modes:
  - Web (npm run dev / npm run build): Standard SPA with browser APIs
  - Wails (wails dev / wails build): Desktop app with native backend

Key Configuration:
  - React plugin for JSX/TSX support
  - Path aliases (@/ maps to project root)
  - Environment variable handling
  - Development server on port 3000

Author: QR Studio Team
Created: 2025-12-16
Updated: 2025-12-16

================================================================================
*/

import path from 'path';
import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, '.', '');
    
    // Determine if we're in Wails mode
    const isWailsMode = process.env.WAILS_BUILD === 'true';
    
    return {
      // Development server configuration
      server: {
        port: 3000,
        host: '0.0.0.0',
        // Strict port ensures consistent URL for Wails dev mode
        strictPort: true,
      },
      
      // Build configuration
      build: {
        // Output directory - Wails expects 'dist' in the frontend directory
        outDir: 'dist',
        // Generate sourcemaps for development builds
        sourcemap: mode === 'development',
        // Ensure clean output
        emptyOutDir: true,
      },
      
      // Plugins
      plugins: [react()],
      
      // Environment variables
      define: {
        'process.env.API_KEY': JSON.stringify(env.GEMINI_API_KEY),
        'process.env.GEMINI_API_KEY': JSON.stringify(env.GEMINI_API_KEY),
        // Flag for frontend to detect build mode
        '__WAILS_MODE__': JSON.stringify(isWailsMode),
      },
      
      // Path resolution
      resolve: {
        alias: {
          '@': path.resolve(__dirname, '.'),
          // Alias for wailsjs bindings (generated by Wails)
          'wailsjs': path.resolve(__dirname, './wailsjs'),
        }
      }
    };
});
