// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistoryEntry(arg1) {
  return window['go']['backend']['App']['AddHistoryEntry'](arg1);
}

export function ClearHistory() {
  return window['go']['backend']['App']['ClearHistory']();
}

export function DeleteTemplate(arg1) {
  return window['go']['backend']['App']['DeleteTemplate'](arg1);
}

export function ExportTemplates() {
  return window['go']['backend']['App']['ExportTemplates']();
}

export function FileExists(arg1) {
  return window['go']['backend']['App']['FileExists'](arg1);
}

export function GetAllSettings() {
  return window['go']['backend']['App']['GetAllSettings']();
}

export function GetAllTemplates() {
  return window['go']['backend']['App']['GetAllTemplates']();
}

export function GetAppDataPath() {
  return window['go']['backend']['App']['GetAppDataPath']();
}

export function GetDesktopPath() {
  return window['go']['backend']['App']['GetDesktopPath']();
}

export function GetHistory(arg1) {
  return window['go']['backend']['App']['GetHistory'](arg1);
}

export function GetHistoryCount() {
  return window['go']['backend']['App']['GetHistoryCount']();
}

export function GetHistoryStats() {
  return window['go']['backend']['App']['GetHistoryStats']();
}

export function GetImageFilters() {
  return window['go']['backend']['App']['GetImageFilters']();
}

export function GetSetting(arg1) {
  return window['go']['backend']['App']['GetSetting'](arg1);
}

export function GetSettingBool(arg1) {
  return window['go']['backend']['App']['GetSettingBool'](arg1);
}

export function GetSettingInt(arg1) {
  return window['go']['backend']['App']['GetSettingInt'](arg1);
}

export function GetTemplate(arg1) {
  return window['go']['backend']['App']['GetTemplate'](arg1);
}

export function GetTemplateCount() {
  return window['go']['backend']['App']['GetTemplateCount']();
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function ImportTemplates(arg1) {
  return window['go']['backend']['App']['ImportTemplates'](arg1);
}

export function IsDesktopMode() {
  return window['go']['backend']['App']['IsDesktopMode']();
}

export function ReadFile(arg1) {
  return window['go']['backend']['App']['ReadFile'](arg1);
}

export function ResetSettingsToDefaults() {
  return window['go']['backend']['App']['ResetSettingsToDefaults']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveFile'](arg1, arg2);
}

export function SaveTemplate(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SaveTemplate'](arg1, arg2, arg3);
}

export function SaveTemplateWithImages(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['SaveTemplateWithImages'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveTextFile'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['backend']['App']['SetSetting'](arg1, arg2);
}

export function ShowOpenDialog(arg1) {
  return window['go']['backend']['App']['ShowOpenDialog'](arg1);
}

export function ShowSaveDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowSaveDialog'](arg1, arg2);
}
