// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['backend']['DesktopAPI']['ClearHistory']();
}

export function DeleteTemplate(arg1) {
  return window['go']['backend']['DesktopAPI']['DeleteTemplate'](arg1);
}

export function DuplicateTemplate(arg1, arg2, arg3) {
  return window['go']['backend']['DesktopAPI']['DuplicateTemplate'](arg1, arg2, arg3);
}

export function GetAllSettings() {
  return window['go']['backend']['DesktopAPI']['GetAllSettings']();
}

export function GetHistory(arg1) {
  return window['go']['backend']['DesktopAPI']['GetHistory'](arg1);
}

export function GetReleaseInfo() {
  return window['go']['backend']['DesktopAPI']['GetReleaseInfo']();
}

export function GetSetting(arg1) {
  return window['go']['backend']['DesktopAPI']['GetSetting'](arg1);
}

export function GetTemplate(arg1) {
  return window['go']['backend']['DesktopAPI']['GetTemplate'](arg1);
}

export function GetTemplateCount() {
  return window['go']['backend']['DesktopAPI']['GetTemplateCount']();
}

export function GetTemplateDocument(arg1) {
  return window['go']['backend']['DesktopAPI']['GetTemplateDocument'](arg1);
}

export function ImportTemplates(arg1) {
  return window['go']['backend']['DesktopAPI']['ImportTemplates'](arg1);
}

export function ListTemplates() {
  return window['go']['backend']['DesktopAPI']['ListTemplates']();
}

export function OpenTemplatePackage() {
  return window['go']['backend']['DesktopAPI']['OpenTemplatePackage']();
}

export function RenameTemplate(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['RenameTemplate'](arg1, arg2);
}

export function ResetSettings() {
  return window['go']['backend']['DesktopAPI']['ResetSettings']();
}

export function SaveArtifact(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['DesktopAPI']['SaveArtifact'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveTemplate(arg1) {
  return window['go']['backend']['DesktopAPI']['SaveTemplate'](arg1);
}

export function SaveTemplatePackage(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['SaveTemplatePackage'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['SetSetting'](arg1, arg2);
}
