// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {backend} from '../models';
import {services} from '../models';

export function ClearHistory():Promise<number>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DuplicateTemplate(arg1:string,arg2:string,arg3:string):Promise<database.Template>;

export function GetAllSettings():Promise<Record<string, string>>;

export function GetHistory(arg1:number):Promise<Array<backend.SafeHistoryEntry>>;

export function GetReleaseInfo():Promise<backend.ReleaseInfo>;

export function GetSetting(arg1:string):Promise<string>;

export function GetTemplate(arg1:string):Promise<database.Template>;

export function GetTemplateCount():Promise<number>;

export function GetTemplateDocument(arg1:string):Promise<backend.TemplateDocument>;

export function ImportTemplates(arg1:string):Promise<services.TemplateImportResult>;

export function ListTemplates():Promise<Array<services.TemplateSummary>>;

export function OpenTemplatePackage():Promise<string>;

export function RenameTemplate(arg1:string,arg2:string):Promise<void>;

export function ResetSettings():Promise<void>;

export function SaveArtifact(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<number>):Promise<backend.FileOperationResult>;

export function SaveTemplate(arg1:backend.TemplateSaveRequest):Promise<database.Template>;

export function SaveTemplatePackage(arg1:string,arg2:string):Promise<backend.FileOperationResult>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
