// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {services} from '../models';

export function AddHistoryEntry(arg1:database.HistoryEntry):Promise<database.HistoryEntry>;

export function ClearHistory():Promise<number>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function ExportTemplates():Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAllSettings():Promise<Record<string, string>>;

export function GetAllTemplates():Promise<Array<database.Template>>;

export function GetAppDataPath():Promise<string>;

export function GetDesktopPath():Promise<string>;

export function GetHistory(arg1:number):Promise<Array<database.HistoryEntry>>;

export function GetHistoryCount():Promise<number>;

export function GetHistoryStats():Promise<services.HistoryStats>;

export function GetImageFilters():Promise<Array<services.FileFilter>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSettingBool(arg1:string):Promise<boolean>;

export function GetSettingInt(arg1:string):Promise<number>;

export function GetTemplate(arg1:string):Promise<database.Template>;

export function GetTemplateCount():Promise<number>;

export function GetVersion():Promise<string>;

export function ImportTemplates(arg1:string):Promise<number>;

export function IsDesktopMode():Promise<boolean>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function ResetSettingsToDefaults():Promise<void>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string,arg3:string):Promise<database.Template>;

export function SaveTemplateWithImages(arg1:string,arg2:string,arg3:string,arg4:Array<number>,arg5:Array<number>):Promise<database.Template>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ShowOpenDialog(arg1:Array<services.FileFilter>):Promise<string>;

export function ShowSaveDialog(arg1:string,arg2:Array<services.FileFilter>):Promise<string>;
