/*
================================================================================
QR STUDIO - WAILS STORAGE SERVICE IMPLEMENTATION
================================================================================

File: services/wailsStorage.ts
Description: Wails backend implementation of the IStorageService interface.
             This is the storage backend for desktop mode operation.

Features:
  - SQLite persistence via Go backend
  - Binary image storage (no Base64 bloat)
  - Native file dialogs
  - Unlimited storage capacity
  - Full CRUD operations via IPC

Architecture:
  Frontend (TypeScript) --> Wails IPC --> Go Backend --> SQLite

Wails Bindings:
  Wails generates TypeScript bindings in wailsjs/go/backend/App.js
  These bindings are used to call Go methods from JavaScript.

Author: QR Studio Team
Created: 2025-12-16
Updated: 2025-12-16

================================================================================
*/

import { QRSettings } from '../types';
import type { IStorageService } from './storage';
import { DEFAULT_SETTINGS } from './storage';

// Wails runtime type declarations
// These are generated by Wails and imported dynamically
declare global {
  interface Window {
    go?: {
      backend: {
        App: {
          // Template methods
          GetAllTemplates(): Promise<any[]>;
          GetTemplate(id: string): Promise<any>;
          SaveTemplate(id: string, name: string, settingsJSON: string): Promise<any>;
          SaveTemplateWithImages(id: string, name: string, settingsJSON: string, logoData: number[], backgroundData: number[]): Promise<any>;
          DeleteTemplate(id: string): Promise<void>;
          ImportTemplates(jsonData: string): Promise<number>;
          ExportTemplates(): Promise<string>;
          GetTemplateCount(): Promise<number>;
          
          // Settings methods
          GetSetting(key: string): Promise<string>;
          SetSetting(key: string, value: string): Promise<void>;
          GetAllSettings(): Promise<Record<string, string>>;
          
          // Export methods
          ShowSaveDialog(defaultFilename: string, filters: any[]): Promise<string>;
          ShowOpenDialog(filters: any[]): Promise<string>;
          SaveFile(path: string, data: number[]): Promise<void>;
          SaveTextFile(path: string, content: string): Promise<void>;
          ReadFile(path: string): Promise<number[]>;
          GetAppDataPath(): Promise<string>;
          GetDesktopPath(): Promise<string>;
          FileExists(path: string): Promise<boolean>;
          GetImageFilters(): Promise<any[]>;
          
          // History methods
          AddHistoryEntry(entry: any): Promise<any>;
          GetHistory(limit: number): Promise<any[]>;
          ClearHistory(): Promise<number>;
          GetHistoryStats(): Promise<any>;
          GetHistoryCount(): Promise<number>;
          
          // Utility methods
          IsDesktopMode(): Promise<boolean>;
          GetVersion(): Promise<string>;
          ResetSettingsToDefaults(): Promise<void>;
        };
      };
    };
  }
}

/**
 * Wails backend implementation of IStorageService.
 * Used in desktop mode when running as a Wails application.
 * 
 * All methods call the Go backend via Wails IPC bindings.
 */
export class WailsStorageService implements IStorageService {
  /**
   * Gets the Wails backend binding.
   * Throws if not available (not running in Wails).
   */
  private get backend() {
    if (!window.go?.backend?.App) {
      throw new Error('Wails backend not available');
    }
    return window.go.backend.App;
  }

  // =========================================================================
  // TEMPLATE OPERATIONS
  // =========================================================================

  /**
   * Retrieves all saved templates from the Go backend.
   * The backend returns TemplateListItem without binary data for efficiency.
   * Use getTemplate(id) to get full template data.
   * 
   * @returns Promise resolving to array of templates
   */
  async getTemplates(): Promise<QRSettings[]> {
    try {
      console.log('[WailsStorage] getTemplates called');
      const templates = await this.backend.GetAllTemplates();
      console.log('[WailsStorage] getTemplates received', templates?.length, 'templates');
      // Use arrow function to preserve 'this' context
      return templates.map((t) => this.mapBackendTemplate(t));
    } catch (error) {
      console.error('Failed to get templates from backend:', error);
      return [];
    }
  }

  /**
   * Retrieves a single template by ID with full data.
   * Includes binary image data converted to Base64 for frontend use.
   * 
   * @param id - Template ID to retrieve
   * @returns Promise resolving to template or null if not found
   */
  async getTemplate(id: string): Promise<QRSettings | null> {
    try {
      const template = await this.backend.GetTemplate(id);
      if (!template) {
        return null;
      }
      return this.mapBackendTemplate(template);
    } catch (error) {
      console.error(`Failed to get template '${id}':`, error);
      return null;
    }
  }

  /**
   * Saves a new template or updates an existing one.
   * Converts frontend QRSettings to backend format.
   * 
   * @param template - Template data to save
   * @returns Promise resolving to saved template with ID
   */
  async saveTemplate(template: QRSettings): Promise<QRSettings> {
    try {
      console.log('[WailsStorage] saveTemplate called', { id: template.id, name: template.name });
      
      // Extract binary image data from settings (ensure arrays, not null)
      const logoData = template.image ? 
        (this.dataUrlToBytes(template.image) || []) : [];
      
      const backgroundData = template.backgroundOptions?.image ? 
        (this.dataUrlToBytes(template.backgroundOptions.image) || []) : [];

      console.log('[WailsStorage] Image data extracted', { 
        hasLogo: logoData.length > 0, 
        hasBackground: backgroundData.length > 0 
      });

      // Create a copy without the Base64 images for JSON storage
      const settingsForJson = { ...template };
      delete settingsForJson.image;
      if (settingsForJson.backgroundOptions) {
        settingsForJson.backgroundOptions = { 
          ...settingsForJson.backgroundOptions,
          image: undefined 
        };
      }

      const id = template.id || '';
      const name = template.name || 'Untitled Template';
      const settingsJSON = JSON.stringify(settingsForJson);

      console.log('[WailsStorage] Calling backend', { id, name, hasImages: logoData.length > 0 || backgroundData.length > 0 });

      // Use SaveTemplateWithImages if we have binary data, otherwise use SaveTemplate
      let saved;
      if (logoData.length > 0 || backgroundData.length > 0) {
        console.log('[WailsStorage] Using SaveTemplateWithImages');
        saved = await this.backend.SaveTemplateWithImages(
          id, 
          name, 
          settingsJSON, 
          logoData, 
          backgroundData
        );
      } else {
        console.log('[WailsStorage] Using SaveTemplate');
        saved = await this.backend.SaveTemplate(id, name, settingsJSON);
      }
      
      console.log('[WailsStorage] Save completed', saved);
      return this.mapBackendTemplate(saved);
    } catch (error) {
      console.error('[WailsStorage] Failed to save template:', error);
      throw error;
    }
  }

  /**
   * Deletes a template by ID.
   * 
   * @param id - Template ID to delete
   */
  async deleteTemplate(id: string): Promise<void> {
    try {
      await this.backend.DeleteTemplate(id);
    } catch (error) {
      console.error(`Failed to delete template '${id}':`, error);
      throw error;
    }
  }

  /**
   * Imports templates from JSON string.
   * The backend handles merging and deduplication.
   * 
   * @param jsonData - JSON string containing template array
   * @returns Promise resolving to number of templates imported
   */
  async importTemplates(jsonData: string): Promise<number> {
    try {
      return await this.backend.ImportTemplates(jsonData);
    } catch (error) {
      console.error('Failed to import templates:', error);
      throw error;
    }
  }

  /**
   * Exports all templates to JSON string.
   * 
   * @returns Promise resolving to formatted JSON string
   */
  async exportTemplates(): Promise<string> {
    try {
      return await this.backend.ExportTemplates();
    } catch (error) {
      console.error('Failed to export templates:', error);
      throw error;
    }
  }

  // =========================================================================
  // SETTINGS OPERATIONS
  // =========================================================================

  /**
   * Retrieves a setting value by key.
   * The backend provides default values for missing settings.
   * 
   * @param key - Setting key
   * @returns Promise resolving to value
   */
  async getSetting(key: string): Promise<string | null> {
    try {
      const value = await this.backend.GetSetting(key);
      return value || DEFAULT_SETTINGS[key] || null;
    } catch (error) {
      console.error(`Failed to get setting '${key}':`, error);
      return DEFAULT_SETTINGS[key] || null;
    }
  }

  /**
   * Saves a setting value.
   * 
   * @param key - Setting key
   * @param value - Setting value
   */
  async setSetting(key: string, value: string): Promise<void> {
    try {
      await this.backend.SetSetting(key, value);
    } catch (error) {
      console.error(`Failed to set setting '${key}':`, error);
      throw error;
    }
  }

  /**
   * Retrieves all settings as a key-value map.
   * 
   * @returns Promise resolving to settings map
   */
  async getAllSettings(): Promise<Record<string, string>> {
    try {
      return await this.backend.GetAllSettings();
    } catch (error) {
      console.error('Failed to get all settings:', error);
      return { ...DEFAULT_SETTINGS };
    }
  }

  // =========================================================================
  // UTILITY METHODS
  // =========================================================================

  /**
   * Returns true for Wails service (in desktop mode).
   */
  isDesktopMode(): boolean {
    return true;
  }

  /**
   * Returns the template count.
   * 
   * @returns Promise resolving to number of saved templates
   */
  async getTemplateCount(): Promise<number> {
    try {
      return await this.backend.GetTemplateCount();
    } catch (error) {
      console.error('Failed to get template count:', error);
      return 0;
    }
  }

  // =========================================================================
  // HELPER METHODS
  // =========================================================================

  /**
   * Maps a backend template to frontend QRSettings format.
   * Parses the settingsJson and handles image data conversion.
   * 
   * @param backendTemplate - Template from Go backend
   * @returns QRSettings for frontend use
   */
  private mapBackendTemplate(backendTemplate: any): QRSettings {
    // Parse the settings JSON if it's a string
    let settings: QRSettings;
    
    if (typeof backendTemplate.settingsJson === 'string') {
      settings = JSON.parse(backendTemplate.settingsJson);
    } else if (backendTemplate.settingsJson) {
      settings = backendTemplate.settingsJson;
    } else {
      // Fallback: treat the entire object as settings
      settings = backendTemplate as QRSettings;
    }

    // Ensure ID and name are set
    settings.id = backendTemplate.id || settings.id;
    settings.name = backendTemplate.name || settings.name;

    // Handle binary image data conversion to Base64 if present
    // (Backend sends as byte array, we need data URL for frontend)
    if (backendTemplate.logoData && backendTemplate.logoData.length > 0) {
      settings.image = this.bytesToDataUrl(backendTemplate.logoData, 'image/png');
    }
    
    if (backendTemplate.backgroundData && backendTemplate.backgroundData.length > 0) {
      if (settings.backgroundOptions) {
        settings.backgroundOptions.image = this.bytesToDataUrl(
          backendTemplate.backgroundData, 
          'image/png'
        );
      }
    }

    return settings;
  }

  /**
   * Maps frontend QRSettings to backend template format.
   * Serializes settings to JSON and extracts image data.
   * 
   * @param settings - QRSettings from frontend
   * @returns Backend template object
   */
  private mapToBackendTemplate(settings: QRSettings): any {
    // Extract binary image data from settings
    const logoData = settings.image ? 
      this.dataUrlToBytes(settings.image) : null;
    
    const backgroundData = settings.backgroundOptions?.image ? 
      this.dataUrlToBytes(settings.backgroundOptions.image) : null;

    // Create a copy without the Base64 images for JSON storage
    const settingsForJson = { ...settings };
    delete settingsForJson.image;
    if (settingsForJson.backgroundOptions) {
      settingsForJson.backgroundOptions = { 
        ...settingsForJson.backgroundOptions,
        image: undefined 
      };
    }

    return {
      id: settings.id || '',
      name: settings.name || 'Untitled Template',
      settingsJson: JSON.stringify(settingsForJson),
      logoData: logoData,
      backgroundData: backgroundData,
    };
  }

  /**
   * Converts byte array to data URL for image display.
   * 
   * @param bytes - Byte array from backend
   * @param mimeType - Image MIME type
   * @returns Data URL string
   */
  private bytesToDataUrl(bytes: number[], mimeType: string): string {
    const binary = String.fromCharCode.apply(null, bytes);
    const base64 = btoa(binary);
    return `data:${mimeType};base64,${base64}`;
  }

  /**
   * Converts data URL to byte array for backend storage.
   * 
   * @param dataUrl - Data URL string
   * @returns Byte array or null if invalid
   */
  private dataUrlToBytes(dataUrl: string): number[] | null {
    try {
      // Extract base64 part from data URL
      const matches = dataUrl.match(/^data:([^;]+);base64,(.+)$/);
      if (!matches) {
        return null;
      }

      const base64 = matches[2];
      const binary = atob(base64);
      const bytes: number[] = new Array(binary.length);
      
      for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
      }

      return bytes;
    } catch (error) {
      console.error('Failed to convert data URL to bytes:', error);
      return null;
    }
  }
}

/**
 * Checks if Wails runtime is available.
 * Used by the factory function to determine which service to use.
 * 
 * @returns True if running in Wails environment
 */
export function isWailsAvailable(): boolean {
  return typeof window !== 'undefined' && 
         window.go !== undefined && 
         window.go.backend !== undefined;
}
